//! Typst export — pure-Rust lowering of a Dashboard to a Typst source
//! document.
//!
//! The HTML render path produces an interactive dashboard; this path produces
//! a static, printable companion. Run `typst compile report.typ` afterward to
//! produce a PDF.
//!
//! # Coverage (v1)
//!
//! - **Paragraph, Table, StatGrid** — fully lowered to native Typst markup.
//! - **Chart** — lowered to a labeled placeholder block carrying the chart
//!   title, kind, source key, row count, and (where the value columns are
//!   numeric) a min/mean/max summary table. Real plot rendering via
//!   `cetz` / `cetz-plot` is planned for a later iteration.
//! - **Filter widgets** — omitted (interactive only).

use std::collections::HashMap;
use std::fmt::Write as _;

use polars::prelude::*;

use crate::charts::{ChartConfig, ChartSpec};
use crate::modules::{ColumnFormat, PageModule, ParagraphSpec, StatGridSpec, TableSpec};
use crate::pages::Page;

/// Build the entire report as a single self-contained Typst source document.
///
/// `frames` carries the same `DataFrame`s used by the HTML render path, keyed
/// by `source_key`. Pages render in insertion order, each as its own Typst
/// section separated by `#pagebreak()`.
///
/// # Example
///
/// ```ignore
/// use rust_to_bokeh::typst_export::build_typst_report;
///
/// let typ = build_typst_report(&dash.pages, &frames, "Quarterly Report");
/// std::fs::write("report.typ", typ)?;
/// // typst compile report.typ
/// ```
#[must_use]
pub fn build_typst_report(
    pages: &[Page],
    frames: &HashMap<String, DataFrame>,
    title: &str,
) -> String {
    let mut out = String::new();

    out.push_str("// RustToBokeh — generated Typst report.\n");
    out.push_str("// Compile with: typst compile report.typ\n\n");
    out.push_str("#set page(paper: \"us-letter\", margin: 0.9in)\n");
    out.push_str("#set text(size: 10pt)\n");
    out.push_str("#set heading(numbering: \"1.\")\n");
    out.push_str("#show heading.where(level: 1): it => block(below: 1em, above: 1.2em)[#text(size: 18pt, weight: \"bold\")[#it.body]]\n");
    out.push_str("#show heading.where(level: 2): it => block(below: 0.6em, above: 0.9em)[#text(size: 13pt, weight: \"semibold\")[#it.body]]\n");
    out.push_str("#set table(stroke: 0.5pt + luma(160), inset: 6pt, align: left)\n\n");

    if !title.is_empty() {
        writeln!(
            out,
            "#align(center)[#text(size: 26pt, weight: \"bold\", \"{}\")]",
            esc_str(title),
        )
        .unwrap();
        out.push_str("#v(0.4em)\n");
        out.push_str("#align(center)[#text(size: 10pt, fill: luma(120), \"Generated by RustToBokeh\")]\n\n");
        out.push_str("#pagebreak()\n\n");
    }

    out.push_str("#outline(depth: 2)\n\n");
    out.push_str("#pagebreak()\n\n");

    for (i, page) in pages.iter().enumerate() {
        if i > 0 {
            out.push_str("#pagebreak()\n\n");
        }
        writeln!(out, "= {}", esc_markup(&page.title)).unwrap();
        out.push('\n');
        if let Some(cat) = &page.category {
            writeln!(out, "_{}_", esc_markup(cat)).unwrap();
            out.push('\n');
        }

        // Render modules in row-major grid order (top-to-bottom, left-to-right).
        let mut order: Vec<usize> = (0..page.modules.len()).collect();
        order.sort_by_key(|&k| {
            let g = match &page.modules[k] {
                PageModule::Chart(s) => &s.grid,
                PageModule::Paragraph(s) => &s.grid,
                PageModule::Table(s) => &s.grid,
                PageModule::StatGrid(s) => &s.grid,
            };
            (g.row, g.col)
        });

        for &k in &order {
            lower_module(&mut out, &page.modules[k], frames);
            out.push('\n');
        }
    }

    out
}

fn lower_module(out: &mut String, module: &PageModule, frames: &HashMap<String, DataFrame>) {
    match module {
        PageModule::Paragraph(p) => lower_paragraph(out, p),
        PageModule::Table(t) => match frames.get(&t.source_key) {
            Some(df) => lower_table(out, t, df),
            None => {
                writeln!(
                    out,
                    "#block(stroke: 0.5pt, inset: 8pt)[_Missing data for table source `{}`_]",
                    esc_markup(&t.source_key),
                )
                .unwrap();
            }
        },
        PageModule::StatGrid(g) => lower_stat_grid(out, g),
        PageModule::Chart(c) => lower_chart(out, c, frames),
    }
}

fn lower_paragraph(out: &mut String, p: &ParagraphSpec) {
    if let Some(title) = &p.title {
        writeln!(out, "== {}", esc_markup(title)).unwrap();
        out.push('\n');
    }
    for para in p.text.split("\n\n") {
        let trimmed = para.trim();
        if !trimmed.is_empty() {
            out.push_str(&esc_markup(trimmed));
            out.push_str("\n\n");
        }
    }
}

fn lower_stat_grid(out: &mut String, g: &StatGridSpec) {
    if g.items.is_empty() {
        return;
    }
    let n = g.items.len();
    writeln!(
        out,
        "#grid(\n  columns: {n},\n  column-gutter: 1em,\n  row-gutter: 0.4em,",
    )
    .unwrap();
    out.push_str("  ");
    for (i, item) in g.items.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        write!(
            out,
            "[#text(size: 8pt, fill: luma(110), upper(\"{}\"))]",
            esc_str(&item.label),
        )
        .unwrap();
    }
    out.push_str(",\n  ");
    for (i, item) in g.items.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        match &item.suffix {
            Some(s) if !s.is_empty() => write!(
                out,
                "[#text(size: 14pt, weight: \"bold\", \"{}\")#text(size: 9pt, fill: luma(120), \" {}\")]",
                esc_str(&item.value),
                esc_str(s),
            )
            .unwrap(),
            _ => write!(
                out,
                "[#text(size: 14pt, weight: \"bold\", \"{}\")]",
                esc_str(&item.value),
            )
            .unwrap(),
        }
    }
    out.push_str(",\n)\n");
}

fn lower_table(out: &mut String, t: &TableSpec, df: &DataFrame) {
    if t.columns.is_empty() {
        return;
    }
    if !t.title.is_empty() {
        writeln!(out, "== {}", esc_markup(&t.title)).unwrap();
        out.push('\n');
    }

    let n_cols = t.columns.len();
    writeln!(out, "#table(").unwrap();
    writeln!(out, "  columns: {n_cols},").unwrap();
    out.push_str("  table.header(");
    for (i, col) in t.columns.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        write!(out, "[*{}*]", esc_markup(&col.label)).unwrap();
    }
    out.push_str("),\n");

    for row in 0..df.height() {
        out.push_str("  ");
        for (i, col_def) in t.columns.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let cell = match df.column(&col_def.key) {
                Ok(series) => format_cell(series, row, &col_def.format),
                Err(_) => String::new(),
            };
            write!(out, "[{}]", esc_markup(&cell)).unwrap();
        }
        out.push_str(",\n");
    }
    out.push_str(")\n");
}

fn lower_chart(out: &mut String, spec: &ChartSpec, frames: &HashMap<String, DataFrame>) {
    if !spec.title.is_empty() {
        writeln!(out, "== {}", esc_markup(&spec.title)).unwrap();
        out.push('\n');
    }
    let kind = spec.config.chart_type_str();
    let rows = frames.get(&spec.source_key).map(DataFrame::height).unwrap_or(0);

    out.push_str("#block(stroke: (paint: luma(180), thickness: 0.5pt), radius: 2pt, inset: 10pt, fill: luma(248), width: 100%)[\n");
    writeln!(
        out,
        "  #text(size: 8pt, fill: luma(100), upper(\"chart · {}\")) \\",
        esc_str(kind),
    )
    .unwrap();
    writeln!(
        out,
        "  #text(size: 11pt, weight: \"semibold\", \"{}\") \\",
        esc_str(&spec.title),
    )
    .unwrap();
    writeln!(
        out,
        "  #text(size: 9pt, fill: luma(120), \"source: {} · {} rows\")",
        esc_str(&spec.source_key),
        rows,
    )
    .unwrap();

    if let Some(df) = frames.get(&spec.source_key) {
        let summary = chart_summary(spec, df);
        if !summary.is_empty() {
            out.push_str("\n  #v(0.5em)\n  ");
            out.push_str(&summary);
            out.push('\n');
        }
    }
    out.push_str("]\n");
}

/// Produce a Typst snippet summarising the data behind a chart, when the kind
/// has obvious numeric value columns. Returns an empty string when the kind
/// is unsupported (box plot, density, bubble's mixed columns).
fn chart_summary(spec: &ChartSpec, df: &DataFrame) -> String {
    let cols: Vec<String> = match &spec.config {
        ChartConfig::Line(c) => c.y_cols.clone(),
        ChartConfig::Scatter(c) => vec![c.y_col.clone()],
        ChartConfig::Bubble(c) => vec![c.y_col.clone(), c.size_col.clone()],
        ChartConfig::HBar(c) => vec![c.value_col.clone()],
        ChartConfig::GroupedBar(c) => vec![c.value_col.clone()],
        ChartConfig::Pie(c) => vec![c.value_col.clone()],
        ChartConfig::Histogram(_) => vec!["count".to_string()],
        ChartConfig::BoxPlot(_) | ChartConfig::Density(_) => return String::new(),
    };

    let rows: Vec<(String, f64, f64, f64)> = cols
        .into_iter()
        .filter_map(|name| numeric_summary(df, &name).map(|(mn, av, mx)| (name, mn, av, mx)))
        .collect();
    if rows.is_empty() {
        return String::new();
    }

    let mut s = String::from(
        "#table(columns: 4, table.header([*Series*], [*Min*], [*Mean*], [*Max*]),\n",
    );
    for (name, mn, av, mx) in rows {
        let _ = writeln!(
            s,
            "  [{}], [{:.4}], [{:.4}], [{:.4}],",
            esc_markup(&name),
            mn,
            av,
            mx,
        );
    }
    s.push(')');
    s
}

fn numeric_summary(df: &DataFrame, col: &str) -> Option<(f64, f64, f64)> {
    let series = df.column(col).ok()?;
    let f: Vec<f64> = match series.dtype() {
        DataType::Float64 => series.f64().ok()?.into_iter().flatten().collect(),
        DataType::Float32 => series
            .f32()
            .ok()?
            .into_iter()
            .flatten()
            .map(f64::from)
            .collect(),
        DataType::Int64 => series
            .i64()
            .ok()?
            .into_iter()
            .flatten()
            .map(|v| v as f64)
            .collect(),
        DataType::Int32 => series
            .i32()
            .ok()?
            .into_iter()
            .flatten()
            .map(f64::from)
            .collect(),
        DataType::UInt32 => series
            .u32()
            .ok()?
            .into_iter()
            .flatten()
            .map(f64::from)
            .collect(),
        DataType::UInt64 => series
            .u64()
            .ok()?
            .into_iter()
            .flatten()
            .map(|v| v as f64)
            .collect(),
        _ => return None,
    };
    if f.is_empty() {
        return None;
    }
    let min = f.iter().copied().fold(f64::INFINITY, f64::min);
    let max = f.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let mean = f.iter().sum::<f64>() / f.len() as f64;
    Some((min, mean, max))
}

fn format_cell(series: &polars::prelude::Column, row: usize, fmt: &ColumnFormat) -> String {
    let raw_val: Option<f64> = match series.dtype() {
        DataType::Float32 => series.f32().ok().and_then(|s| s.get(row)).map(f64::from),
        DataType::Float64 => series.f64().ok().and_then(|s| s.get(row)),
        DataType::Int32 => series.i32().ok().and_then(|s| s.get(row)).map(f64::from),
        DataType::Int64 => series.i64().ok().and_then(|s| s.get(row)).map(|v| v as f64),
        DataType::UInt32 => series.u32().ok().and_then(|s| s.get(row)).map(f64::from),
        DataType::UInt64 => series.u64().ok().and_then(|s| s.get(row)).map(|v| v as f64),
        _ => None,
    };
    if raw_val.is_none() {
        if let Ok(ca) = series.str() {
            return ca.get(row).unwrap_or("").to_string();
        }
        return series.get(row).map(|v| format!("{v}")).unwrap_or_default();
    }
    let v = raw_val.unwrap_or(0.0);
    match fmt {
        ColumnFormat::Text => format!("{v}"),
        ColumnFormat::Number { decimals } => {
            format!("{:.prec$}", v, prec = *decimals as usize)
        }
        ColumnFormat::Currency { symbol, decimals } => {
            let abs = v.abs();
            let sign = if v < 0.0 { "-" } else { "" };
            format!("{sign}{symbol}{:.prec$}", abs, prec = *decimals as usize)
        }
        ColumnFormat::Percent { decimals } => {
            format!("{:.prec$}%", v, prec = *decimals as usize)
        }
    }
}

/// Escape a string for safe inclusion in Typst markup (between `[ ]` content
/// blocks). Conservatively prefixes `\` to every character that has syntactic
/// meaning in markup mode, so plain text never collides with parser rules.
fn esc_markup(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' | '#' | '[' | ']' | '<' | '>' | '@' | '*' | '_' | '`' | '$' | '~' => {
                out.push('\\');
                out.push(c);
            }
            _ => out.push(c),
        }
    }
    out
}

/// Escape a string for safe inclusion inside a Typst double-quoted string
/// literal.
fn esc_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::charts::{ChartSpecBuilder, HBarConfig, LineConfig};
    use crate::handle::DfHandle;
    use crate::modules::{ParagraphSpec, StatGridSpec, StatItem, TableColumn, TableSpec};
    use crate::pages::PageBuilder;

    fn empty_frames() -> HashMap<String, DataFrame> {
        HashMap::new()
    }

    #[test]
    fn esc_markup_escapes_special_chars() {
        assert_eq!(esc_markup("a#b[c]"), "a\\#b\\[c\\]");
        assert_eq!(esc_markup("plain"), "plain");
        assert_eq!(esc_markup("a*b_c"), "a\\*b\\_c");
    }

    #[test]
    fn esc_str_escapes_quotes_and_backslashes() {
        assert_eq!(esc_str("hi \"there\""), "hi \\\"there\\\"");
        assert_eq!(esc_str("a\\b"), "a\\\\b");
        assert_eq!(esc_str("line\nbreak"), "line\\nbreak");
    }

    #[test]
    fn empty_dashboard_emits_preamble_and_outline() {
        let typ = build_typst_report(&[], &empty_frames(), "My Report");
        assert!(typ.contains("#set page("));
        assert!(typ.contains("My Report"));
        assert!(typ.contains("#outline"));
    }

    #[test]
    fn page_renders_heading() {
        let cfg = HBarConfig::builder()
            .category("c")
            .value("v")
            .x_label("X")
            .build()
            .unwrap();
        let page = PageBuilder::new("p1", "Page One", "P1", 1)
            .chart(
                ChartSpecBuilder::hbar("Chart A", &DfHandle::new("d"), cfg)
                    .at(0, 0, 1)
                    .build(),
            )
            .build()
            .unwrap();

        let typ = build_typst_report(&[page], &empty_frames(), "");
        assert!(typ.contains("= Page One"));
        assert!(typ.contains("Chart A"));
        assert!(typ.contains("hbar"));
    }

    #[test]
    fn paragraph_lowers_with_title_and_body() {
        let para = ParagraphSpec::new("First.\n\nSecond.")
            .title("Intro")
            .at(0, 0, 1)
            .build();
        let page = PageBuilder::new("p", "P", "P", 1)
            .paragraph(para)
            .build()
            .unwrap();

        let typ = build_typst_report(&[page], &empty_frames(), "");
        assert!(typ.contains("== Intro"));
        assert!(typ.contains("First."));
        assert!(typ.contains("Second."));
    }

    #[test]
    fn stat_grid_lowers_to_typst_grid() {
        let grid = StatGridSpec::new()
            .item(StatItem::new("DURATION", "72").suffix("h"))
            .item(StatItem::new("PEAK", "4.2"))
            .at(0, 0, 1)
            .build();
        let page = PageBuilder::new("p", "P", "P", 1)
            .stat_grid(grid)
            .build()
            .unwrap();

        let typ = build_typst_report(&[page], &empty_frames(), "");
        assert!(typ.contains("#grid("));
        assert!(typ.contains("DURATION"));
        assert!(typ.contains("PEAK"));
        assert!(typ.contains("\"72\""));
    }

    #[test]
    fn table_lowers_with_header_and_rows() {
        let df = df![
            "name" => ["Alice", "Bob"],
            "score" => [95.0f64, 87.5],
        ]
        .unwrap();
        let mut frames = HashMap::new();
        frames.insert("data".to_string(), df);

        let tbl = TableSpec::new("Scores", &DfHandle::new("data"))
            .column(TableColumn::text("name", "Name"))
            .column(TableColumn::number("score", "Score", 1))
            .at(0, 0, 1)
            .build();
        let page = PageBuilder::new("p", "P", "P", 1)
            .table(tbl)
            .build()
            .unwrap();

        let typ = build_typst_report(&[page], &frames, "");
        assert!(typ.contains("== Scores"));
        assert!(typ.contains("#table("));
        assert!(typ.contains("Alice"));
        assert!(typ.contains("95.0"));
    }

    #[test]
    fn chart_summary_includes_min_mean_max_for_line() {
        let df = df![
            "x" => [1i64, 2, 3, 4],
            "y" => [10.0f64, 20.0, 30.0, 40.0],
        ]
        .unwrap();
        let mut frames = HashMap::new();
        frames.insert("d".to_string(), df);

        let cfg = LineConfig::builder()
            .x("x")
            .y_cols(&["y"])
            .y_label("Y")
            .build()
            .unwrap();
        let page = PageBuilder::new("p", "P", "P", 1)
            .chart(
                ChartSpecBuilder::line("Trend", &DfHandle::new("d"), cfg)
                    .at(0, 0, 1)
                    .build(),
            )
            .build()
            .unwrap();

        let typ = build_typst_report(&[page], &frames, "");
        assert!(typ.contains("Trend"));
        assert!(typ.contains("Min"));
        assert!(typ.contains("Mean"));
        assert!(typ.contains("Max"));
        assert!(typ.contains("10.0000"));
        assert!(typ.contains("40.0000"));
    }

    #[test]
    fn missing_table_source_produces_warning_block() {
        let tbl = TableSpec::new("Missing", &DfHandle::new("nonexistent"))
            .column(TableColumn::text("x", "X"))
            .at(0, 0, 1)
            .build();
        let page = PageBuilder::new("p", "P", "P", 1)
            .table(tbl)
            .build()
            .unwrap();

        let typ = build_typst_report(&[page], &empty_frames(), "");
        assert!(typ.contains("Missing data for table source"));
    }

    #[test]
    fn pages_separated_by_pagebreak() {
        let mk_page = |slug: &str, title: &str| {
            let cfg = HBarConfig::builder()
                .category("c")
                .value("v")
                .x_label("X")
                .build()
                .unwrap();
            PageBuilder::new(slug, title, slug, 1)
                .chart(
                    ChartSpecBuilder::hbar("c", &DfHandle::new("d"), cfg)
                        .at(0, 0, 1)
                        .build(),
                )
                .build()
                .unwrap()
        };

        let typ = build_typst_report(&[mk_page("a", "Alpha"), mk_page("b", "Beta")], &empty_frames(), "");
        assert!(typ.contains("= Alpha"));
        assert!(typ.contains("= Beta"));
        let breaks = typ.matches("#pagebreak()").count();
        assert!(breaks >= 1, "expected pagebreak between pages, got {breaks}");
    }
}
